### ISSUE TITLE
Error: URL shortener failed with 403

### ISSUE THREAD

**Issue by sanmi** [bfkeinberg/route-forecast#19]
Steps to reproduce:
* enter a route with gps number
* 
<img width="543" alt="screen shot 2018-04-17 at 6 26 01 am" src="https://user-images.githubusercontent.com/541993/38872541-5c66bb0c-4208-11e8-8b6c-456034c98342.png">
hit tab

**Comment by bfkeinberg** [comment]
Google is shutting down their URL shortener; I'll probably turn off this feature until I've time to integrate a replacement service.

**Comment by wrbird** [comment]
I'm receiving this error message.  What am I doing wrong?
