### ISSUE TITLE
Various Issues

### ISSUE THREAD

**Issue by wrbird** [bfkeinberg/route-forecast#23]
1. Entering RWGPS number yields "Error: URL shortener failed with 403 Forbidden" but still seems to find forecast
2. Can't add control point because data fields are behind the column headers
3. Forecast map doesn't display

**Comment by wrbird** [comment]
Above issues reported using Firefox.  Everything seems to be working correctly when using Chrome.

**Comment by wrbird** [comment]
I added a control point 52 miles into my route and the Estimated Arrival Time is the same time as my start time.  This can't be right.  What is banked time?

**Comment by bfkeinberg** [comment]
I'm looking into the Firefox thing. I use a third-party library for the control data table, it seems to be behaving very oddly under Firefox. I'll see if there's any updates.

**Comment by bfkeinberg** [comment]
Banked time is relevant if the ride that you're forecasting is a brevet. It indicates how you're doing relative to the brevet time limits.

https://rusa.org/pages/rulesForRiders
