### ISSUE TITLE
Climb Adjusted Pace

### ISSUE THREAD

**Issue by wrbird** [bfkeinberg/route-forecast#25]
I'm unclear as to what value I should select for the climb adjusted pace.  My standard pace (avg speed) on flats is 16 mph (D rating on flats).  If I go to https://westernwheelersbicycleclub.wildapricot.org/ride_rating_calculator and enter the data for a particular ride I get a hilliness of 3 and 13 mph avg for a D rating.  So do I select D/16 for the pace or C-/13?

**Comment by wrbird** [comment]
After using data from past rides I get the closest estimated values to actual values when using D/16 pace.  So I'm guessing this is what I'm supposed to select.  Would that be correct?

**Comment by bfkeinberg** [comment]
Yes, that's right. The letter pace that you select takes hilliness into account, so the number corresponding is only applicable on a flat route, as you observed.

**Comment by wrbird** [comment]
You have a great website, good job.
