### ISSUE TITLE
This page can't load Google Maps correctly

### ISSUE THREAD

**Issue by sanmi** [bfkeinberg/route-forecast#27]
Steps to reproduce:
I'm seeing this error when I go to: https://goo.gl/BEUKys

![image](https://user-images.githubusercontent.com/541993/43672061-d6f92498-975a-11e8-96d0-b78cdca4e770.png)

**Comment by bfkeinberg** [comment]
Google bugging me to give them billing information. Sigh. I gave in. Hopefully they don't use it.
