### ISSUE TITLE
Generated Link 

### ISSUE THREAD

**Issue by wrbird** [bfkeinberg/route-forecast#30]
When using the generated link to view web page it crashes your website.

**Comment by bfkeinberg** [comment]
OK, I'll take a look.

**Comment by wrbird** [comment]
Thanks for your quick response.  Here's the link that was generated and crashes:
https://goo.gl/difdMy

**Comment by bfkeinberg** [comment]
I just pushed a fix. Should do the trick.

**Comment by wrbird** [comment]
I can't even access the website now. I get a server error, try again in 30 seconds. I tried that multiple times with no success.

**Comment by bfkeinberg** [comment]
What the heck, that's weird. Let me check the server and see.

**Comment by wrbird** [comment]
Thanks!  You developed an awesome website.  Looking forward to it being up again.  Keep up the good work!

**Comment by bfkeinberg** [comment]
Try it now?

**Comment by wrbird** [comment]
I'm now able to access the website, but the generated link (https://goo.gl/2yiRnk) still isn't working.  It's no longer crashing the website, but it's not showing the forecast like it used to.  On the page from the link the Pace is correctly populated with the previous value and the RideWithGPS field has the correct route, but the Starting time isn't what it was set to before. Also, when I click on the Find forecast button on the page that was opened from the link it doesn't do anything.

I would like to donate for your efforts, do you have a way to do that?

**Comment by wrbird** [comment]
xxx

**Comment by wrbird** [comment]
Sorry, didn't mean to close the issue.

**Comment by wrbird** [comment]
Any updates on this issue?

**Comment by bfkeinberg** [comment]
Might not be fixed completely until weekend. Will try tonight.

**Comment by bfkeinberg** [comment]
For now if you tab out of the field that has the route number it will load
the route. I'm digging into why that's the only way.

**Comment by wrbird** [comment]
Tabbing out does load the page, however, when using the link it still doesn't populate the date and time field correctly like it used to.  But thanks for working on this.  I don't know why there's issues now, it worked great last summer.

**Comment by bfkeinberg** [comment]
Loading should be fixed now. I'm not sure what changed out from under me either. I'll check the date/time issue next.

If you want to contribute, I guess you could paypal me anything you feel is appropriate? Email is brian@feinberg.com.  :)

**Comment by wrbird** [comment]
Yes, I confirmed everything works now except the date and time as you already knew. If you get a chance to add the toggle for feels like temp, let me know. Thanks! 


I just linked my bank account to PayPal so once they verify everything in the next couple of days I'll send you a donation of appreciation for your hard work!

**Comment by wrbird** [comment]
Just a heads up that I noticed when using the generated link the information in the starting time isn't correct but the time shown in the forecast section is.  So I'm not sure if this is even a problem anymore.

**Comment by bfkeinberg** [comment]
This ought to be fixed now.
