### ISSUE TITLE
Feels like temps

### ISSUE THREAD

**Issue by wrbird** [bfkeinberg/route-forecast#32]
I like how the wind speed toggles with wind gusts. It would be great if the temperature toggled with the feels like temperature. Is this something that can be added?

**Comment by bfkeinberg** [comment]
It depends on whether I can get that in my forecast data feed. I'll check.

**Comment by bfkeinberg** [comment]
Although the Dark Sky docs indicate it wouldn't be present, it seems to be. I can add this.

**Comment by wrbird** [comment]
Thanks for looking into this!  Can't wait to see it.

**Comment by wrbird** [comment]
Does those mean the temperature column now toggles between temperature and feels like temperature? When I just tried it it's not toggling.

**Comment by bfkeinberg** [comment]
In current release. Check it out now.

**Comment by wrbird** [comment]
Awesome! Works great! I also liked how you changed the Pace and it's tool tip. Very clear now.
