### ISSUE TITLE
"Minutes lost" gives crazy results

### ISSUE THREAD

**Issue by palincss** [bfkeinberg/route-forecast#33]
For route 29156459 today w/13-15 mph winds, pace A 10 gives me 209683 minutes lost to wind.  Changing the pace to B12 changes that to 92 minutes.  Changing it back to A10 and getting forecast again gives me that 209683 number again.  209 thousand minutes lost to the wind on a 30 mile ride is absurd and has to be a bug.

**Comment by bfkeinberg** [comment]
Yes, it certainly sounds wrong, I'll look.

**Comment by bfkeinberg** [comment]
Actually, if you could give me the URL you used, that would be super helpful.

**Comment by palincss** [comment]
https://goo.gl/s1hR1J  shows the same route with today's forecast start time of 7 am, with 16 mph winds declining to 14 mph over the course of the morning. A/10 pace results in 2812 minutes lost due to the wind.  Not as off the wall as 600,000 min the other day, but still way out of range.  Changing pace to B/12 makes that number 256 min.  

On a related subject, is there a way I can contact you directly?  I have some suggestions for improving the online documentation and have some questions about the use of the control point list.  My email is palincss@his.com

**Comment by bfkeinberg** [comment]
One point with this particular forecast is that the forecasted wind gust speed is very high. I try to factor in the wind gusts, as that makes a difference.

**Comment by bfkeinberg** [comment]
I _think_ this could have to do with the tool taking into account wind gusts overly much. I reduced the effect of that. Wind effects are very hard to estimate anyhow.
