### ISSUE TITLE
Finish time & Time lost to wind are wildly off

### ISSUE THREAD

**Issue by palincss** [bfkeinberg/route-forecast#37]
Here's a ride I'm planning to lead on Saturday morning, 10:30 am, a 40 mile ride.  I posted the link to the route forecast app as part of the ride description.   The URL is https://goo.gl/qpThD5  I'm adding a screen shot to show that right now, the app thinks this 40 mi ride leaving at 10:30 is going to finish at 9:02 pm, after having hit the checkpoint at mi 26.4 at 6:30 pm, with a total of 322 minutes lost to a 11-13 mph wind.  Meanwhile, in the wind& weather forecast column, the app thinks we'll reach the last mile at 3:40 pm.  But if I change the pace to B12, it says we'll arrive at 2:49 pm (even though the wind & weather table says we'll reach mile 42 at 3:40 pm.

![Screenshot_2019-03-26 Forecast for Aviation Club, Chaptico Baptist Church](https://user-images.githubusercontent.com/48860113/55045679-0a5e5380-5015-11e9-9987-5033bf7a912b.png)

**Comment by bfkeinberg** [comment]
There's seems to be something screwy going on specifically with that speed.
I can see that by jumping between 14-12-10 on the speeds, where going from
14 to 12 adds 20 minutes to the arrival time at the second control, but
going from 12 to 10 adds 40 minutes to the arrival time there. And of
course it adds nearly an hour to the finish.

I'm going to test and see if it does have something to do with the wind
gust speeds.
Which are, you will agree, high.

**Comment by bfkeinberg** [comment]
Actually, it's not wind gust effects either. I'm going to try to see if I
can load your route to see how hilly it is. And to explain why it requires
fetching the forecast again to fully update the time estimate.

**Comment by bfkeinberg** [comment]
It's not the added effect of the wind gust so much as just the part that
tries to account for wind at all. Without that, the forecast time is
consistent at 3:40 pm for your finish at 10mph. The question is whether
it's more accurate to take that wind into account.

**Comment by bfkeinberg** [comment]
I'm turning off the adjustment to time made for wind gusts alone. The results were too unpredictable. It will simply highlight the time lost to wind in red if there are gusts more than 25mph.
