### ISSUE TITLE
Generated Link is missing

### ISSUE THREAD

**Issue by wrbird** [bfkeinberg/route-forecast#39]
Just went to cycleroutingforecast and created a forecast and noticed the generated link is no longer there.  I know the last time I was testing this it was.  Did you remove it intentionally?
Thanks for looking into this.

**Comment by bfkeinberg** [comment]
Not intentionally, no. It could be that the google service which does that has finally been shut down. In that case I'll have to work on integrating a replacement.

**Comment by wrbird** [comment]
Yep, you're right. I just read an article that Google just shut down this service. Hopefully integrating something like bit.ly won't be too difficult.

**Comment by bfkeinberg** [comment]
goo.gl is now replaced by bitly.

**Comment by wrbird** [comment]
Just tested it and it's not any different than before.  Error message pops up and quickly disappears with no shortened URL.  Am I doing something wrong?

**Comment by bfkeinberg** [comment]
Maybe your browser is still using the old version. Possibly clearing the
browser cache would help. I just double checked and definitely the new
version is now showing shortened links from bitly.

**Comment by wrbird** [comment]
Thanks for letting me know.  I'll clear the cache and see how it works.  Thanks for updating!

**Comment by wrbird** [comment]
Ok, it works on Chrome, but doesn't work on Firefox.  Firefox is my default browser.

**Comment by bfkeinberg** [comment]
Very odd. I'll have to examine that.

**Comment by bfkeinberg** [comment]
Aha, it is definitely specific to Firefox. Bitly seems to return headers that FF won't accept. Will take further investigation.

**Comment by wrbird** [comment]
Sorry for creating extra work, I sure appreciate your efforts.  This is a great resource!
