### ISSUE TITLE
10 mph is slower but finishes first

### ISSUE THREAD

**Issue by palincss** [bfkeinberg/route-forecast#43]
![10 mph Screenshot from 2019-04-10 18:26:06](https://user-images.githubusercontent.com/48860113/55918002-8208b280-5bbf-11e9-94d3-0f75069d7f87.png)
![11 mph Screenshot from 2019-04-10 18:26:16](https://user-images.githubusercontent.com/48860113/55918005-8634d000-5bbf-11e9-8a11-62203ab9e305.png)
![11 mph Screenshot from 2019-04-10 18:26:29](https://user-images.githubusercontent.com/48860113/55918008-88972a00-5bbf-11e9-80cd-8130074357f8.png)
![12 mph Screenshot from 2019-04-10 18:26:22](https://user-images.githubusercontent.com/48860113/55918013-8b921a80-5bbf-11e9-8d14-07d482a8646d.png)
![13 mph Screenshot from 2019-04-10 18:26:35](https://user-images.githubusercontent.com/48860113/55918016-8df47480-5bbf-11e9-9819-87ccccc0ba76.png)

10 mph average speed finishes first and 11 finishes sooner or later only seconds apart

**Comment by bfkeinberg** [comment]
ok, and doesn't look like wind, given the low number of minutes lost to it.
I will examine.
