### ISSUE TITLE
 Feature Request: less than 10mph

### ISSUE THREAD

**Issue by DDM-Git** [bfkeinberg/route-forecast#47]
Very useful tool, used a couple times for bike rides. I would also like to use this for hiking, but I can not hike at 10 mph :-) Could you add entries less than 10 mph, or allow and edit field? Thanks, nice work.

**Comment by bfkeinberg** [comment]
I don't think that the predictions of time would be accurate in this range, it's easy enough to change the menu, but results may vary.

**Comment by bfkeinberg** [comment]
Dunno if it'll be useful, but I added 3/4/5/6 to the menu.
