### ISSUE TITLE
times in segment table are not sequential

### ISSUE THREAD

**Issue by sanmi** [bfkeinberg/route-forecast#49]
RWGPS route: 31831394
Speed: 13
Start: 8:00am

Observed. 
* Note the last two times in the table: 4:10pm, 3:33pm

![image](https://user-images.githubusercontent.com/541993/73544900-064a5180-43ef-11ea-8910-9212170da28c.png)

**Comment by bfkeinberg** [comment]
OK, that's weird, I'll look.

**Comment by bfkeinberg** [comment]
Darn, looks totally different when I try. 
http://bit.ly/2uRH3si

**Comment by bfkeinberg** [comment]
Never could repro.
