### ISSUE TITLE
Powered by Strava crashes upon "Perform Analysis"

### ISSUE THREAD

**Issue by gvirshup** [bfkeinberg/route-forecast#50]
First time I have tried the Powered by Strava button.
I entered the strava URL https://www.strava.com/activities/3495667865

then upon pressing the button "Perform analysis" app crashes and the screen shows 

{"message":"Bad Request","errors":[{"resource":"Application","field":"redirect_uri","code":"invalid"}]}

![Screen Shot 2020-05-22 at 10 37 23 PM](https://user-images.githubusercontent.com/40897621/82722634-55a5dd80-9c7d-11ea-927a-d0cc79265595.png)
![Screen Shot 2020-05-22 at 10 37 38 PM](https://user-images.githubusercontent.com/40897621/82722636-58a0ce00-9c7d-11ea-8f79-d94887569735.png)

**Comment by gvirshup** [comment]
FYI ride route was
https://bit.ly/3ebeg3n

**Comment by bfkeinberg** [comment]
How curious, I'll look and see if something has expired.

**Comment by bfkeinberg** [comment]
Fixed, it was broken by the new site url. Also I improved the pace display when using Strava analysis.

**Comment by gvirshup** [comment]
FYI
It crashes when I attempt to change the Analysis Interval, I don’t even get the opportunity to click on Perform analysis



On Jun 7, 2020, at 6:00 PM, gary virshup <gvirshup@gmail.com> wrote:

Not quite working for me yet!!


RidewithGPS
https://ridewithgps.com/routes/32898875 <https://ridewithgps.com/routes/32898875>

Strava 
https://www.strava.com/activities/3569345318 <https://www.strava.com/activities/3569345318>

Route Forecast
https://bit.ly/2MFjyZm <https://bit.ly/2MFjyZm>
<Screen Shot 2020-06-07 at 5.59.01 PM.png>



On Jun 7, 2020, at 5:00 PM, bfkeinberg <notifications@github.com <mailto:notifications@github.com>> wrote:


Fixed, it was broken by the new site url. Also I improved the pace display when using Strava analysis.
