### ISSUE TITLE
Times during ride do not calculate correctly

### ISSUE THREAD

**Issue by AROBWW288** [bfkeinberg/route-forecast#54]
I tested different pace MPH's and the times do not match. You are predicting that a given ride will take much longer than what should be calculated. For instance a 60 mile ride at 10 mph comes out to be 12 hours on your system, instead of 6.

**Comment by AROBWW288** [comment]
Try this. To illustrate, I set the speed at 10mph for a 60 mile ride.  The
program takes 12 hours instead of 6.
https://bit.ly/355vvSz

Thanks Alan

**Comment by bfkeinberg** [comment]
I'll take a look. One thing to keep in mind though is that the speed you enter there is climbing adjusted. That speed is your speed on flat ground, and is reduced for climbing. It is the pace from here - 
https://westernwheelersbicycleclub.wildapricot.org/page-1374754

Entering a speed of 10mph means that you would take 6 hours on a completely flat course.

**Comment by bfkeinberg** [comment]
I meant to clear this up earlier. The time estimate uses both the terrain, meaning how much climb is in the route, and the wind forecast. In this case the more important one is the amount of climb, ~4900 feet. That's about 85 feet/mile, which on average makes the effective speed 6 and change. It really depends on the individual climbs, though.
