### ISSUE TITLE
Banked Time Popup

### ISSUE THREAD

**Issue by DDM-Git** [bfkeinberg/route-forecast#56]
When I mouse over "Display Banked Time" the popup for "Metric" seems to display on top of the Banked Time popup. The text says :

"Display units in km, other units displayed in km or degrees C times" 

Note the last word "times", which is the last word in the Banked Time popup text. 

Steps to reproduce:
- move cursor below "Display banked time", near the highlighted text "Control point list for ...." 
- move cursor vertical to show popup

Also, I can get the Banked Time popup to display on top of Metric popup doing this: 
- move cursor over "Metric" to display the popup so the cursor is to the left of "Display banked time" text
- Now slowly move the cursor horizontally toward the "Display banked time" 
- The Banked Time popup will appear on top of the Metric popup

The mouseover areas for the two text fields is probably overlapping.

Running Chrome on a mac with Mojave.

Thanks for rando, it's really nice!!

**Comment by bfkeinberg** [comment]
Interesting. I'm trying to duplicate, but I have not been able, even if I make the browser window fairly small. What is the size of the Chrome window which you are using?

**Comment by DDM-Git** [comment]
2880x1800, 15.4 inch screen, I can reproduce with a full screen window. Also tried on Safari browser and saw the same thing. I have a windows box, I’ll try it out on that one this afternoon.

**Comment by DDM-Git** [comment]
I see the same thing on Windows 10, 1920x1080 screen with chrome and MS Edge browser. Not a big deal, I wouldn't spend too much time on it ;-)
    On Thursday, February 18, 2021, 08:24:48 AM PST, David Marancik <ddm2005@sbcglobal.net> wrote:  
 
 2880x1800, 15.4 inch screen, I can reproduce with a full screen window. Also tried on Safari browser and saw the same thing. I have a windows box, I’ll try it out on that one this afternoon.




On Feb 15, 2021, at 8:40 PM, bfkeinberg <notifications@github.com> wrote:


Interesting. I'm trying to duplicate, but I have not been able, even if I make the browser window fairly small. What is the size of the Chrome window which you are using?

**Comment by bfkeinberg** [comment]
I am still not able to cause any overlaps on my system, but I'll poke around a little with the Chrome devtools to check out what the browser thinks the bounding boxes are. I don't really have control over that, but I do want to see.

**Comment by bfkeinberg** [comment]
Still can't repro any way that I've tried.
