### ISSUE TITLE
Process Not Defined - Analysis

### ISSUE THREAD

**Issue by DDM-Git** [bfkeinberg/route-forecast#66]
Trying to use the ride analysis feature. I saved the tiny URL and opened route planner with it. Then selected powered by Strava and put in my Strava link. Initially had strava route permissions set to "Followers", then switched permission to "everyone". Still only get the "Process Not Defined" error. 

MacOS Big Sur, 11.3.1, with Chrome.

Tried with Safari browser and the error is "Can't find variable: process"

saved route planner : https://bit.ly/3csOIQR
Strava link : https://www.strava.com/activities/5438657385

-Dave

**Comment by bfkeinberg** [comment]
Will investigate.

**Comment by bfkeinberg** [comment]
OK, thanks for finding this, it should be fixed now.
