### ISSUE TITLE
Cannot know windspeed direction near start/end on loop rides

### ISSUE THREAD

**Issue by sanmi** [bfkeinberg/route-forecast#8]
Steps to reproduce:
* choose a route that is a loop on a day where the wind is one direction at the start and a different direction at the end of the ride

Expected result:
* I want to be able to differentiate the predicted wind direction at the start from the direction at the end

Actual:
* you see two wind directions near start/end
* there is no way to know which direction is the start, which is near the end

<img width="212" alt="screen shot 2018-03-09 at 6 42 41 am" src="https://user-images.githubusercontent.com/541993/37212887-468f1390-2365-11e8-9fbe-d3045f189e2c.png">

Suggestion:
* Find a way to visuzalize the map data on the route table.  For example, you could add an arrow next to the text or add text (e.g. N, E, W, S, NE, SW, etc) 

Here's how predictwind.com does wind visualizations.  This is an expensive app that people pay a lot of money for (e.g. fishermen, sailors, surfers)
<img width="1088" alt="screen shot 2018-03-09 at 6 47 58 am" src="https://user-images.githubusercontent.com/541993/37213172-0f172d48-2366-11e8-9143-db3c7fe8871c.png">

**Comment by bfkeinberg** [comment]
This one definitely takes a little more thought.
