### ISSUE TITLE
Please add more pace types

### ISSUE THREAD

**Issue by sanmi** [bfkeinberg/route-forecast#9]
* My pace is a C- but my only choices are B or C
* On a 76 mile ride, this means a difference in end time of 2.5 hours.  A B pace finishes at 8:18p and a C pace finishes at 5:54pm.
* It would be nice to have a C- pace to select

https://goo.gl/fZkZKX

**Comment by bfkeinberg** [comment]
I've been thinking of dropping the letter for entry and just going to a numeric entry field.

**Comment by sanmi** [comment]
thanks!

**Comment by sanmi** [comment]
There is something wrong with the C- pace.  It results in a travel time of 0.  https://goo.gl/aQMLYc

**Comment by bfkeinberg** [comment]
Ah, the table that holds those values was duplicated, when it was meant to be defined once and imported. Fixed.

**Comment by sanmi** [comment]
thanks - it works for me now.
